-- ????????? ??????? "Customers"
ALTER TABLE dbo.customers ADD
ValidFrom DATETIME2 GENERATED ALWAYS AS ROW START HIDDEN
CONSTRAINT DF_customers_ValidFrom DEFAULT SYSUTCDATETIME(),
ValidTo DATETIME2 GENERATED ALWAYS AS ROW END HIDDEN
CONSTRAINT DF_customers_ValidTo DEFAULT CONVERT(DATETIME2, '9999-12-31
23:59:59.9999999'),
PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo);
ALTER TABLE dbo.customers
SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.customers_History));